name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t 3114575344/entrega-continua:entrega-$(date +%s) .

    - name: Push Docker image to Docker Hub
      run: docker push 3114575344/entrega-continua:entrega-$(date +%s)
